language: scala
jdk:
  - oraclejdk8
before_script:
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar -xvf protobuf-2.6.1.tar.gz
  - cd protobuf-2.6.1 && ./configure && make && sudo make install && cd ..
script:
  - sbt clean coverage test coverageReport
after_success:
  - sbt coveralls
